version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

jobs:
  # TODO: dogfood
  lint:
    docker:
      - image: python:3.7.1-alpine3.8
    steps:
      - run: apk add -U git
      - checkout
      - run: pip install pre-commit
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit install-hooks
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: pre-commit run --all-files

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint

      - orb-tools/lint:
          name: lint-orbs-linter
          lint-dir: circleci-orbs/linter
      - orb-tools/pack:
          name: pack-orbs-linter
          source-dir: circleci-orbs/linter
          requires:
            - lint-orbs-linter
      - orb-tools/publish-dev:
          context: org-global
          name: publish-dev-orbs-linter
          orb-name: thekevjames/linter
          requires:
            - lint
            - pack-orbs-linter
      - orb-tools/dev-promote-prod:
          context: org-global
          name: dev-promote-prod-orbs-linter
          orb-name: thekevjames/linter
          # TODO: allow major and minor semver updates
          release: patch
          requires:
            - publish-dev-orbs-linter

      - orb-tools/lint:
          name: lint-orbs-deployment-notifier
          lint-dir: circleci-orbs/deployment-notifier
      - orb-tools/pack:
          name: pack-orbs-deployment-notifier
          source-dir: circleci-orbs/deployment-notifier
          requires:
            - lint-orbs-deployment-notifier
      - orb-tools/publish-dev:
          context: org-global
          name: publish-dev-orbs-deployment-notifier
          orb-name: thekevjames/deployment-notifier
          requires:
            - lint
            - pack-orbs-deployment-notifier
      - orb-tools/dev-promote-prod:
          context: org-global
          name: dev-promote-prod-orbs-deployment-notifier
          orb-name: thekevjames/deployment-notifier
          # TODO: allow major and minor semver updates
          release: patch
          requires:
            - publish-dev-orbs-deployment-notifier
