version: 2

# orbs:
#   orb-tools: circleci/orb-tools@7.3.0

jobs:
  lint:
    docker:
      - image: python:3.7.1-alpine3.8
    steps:
      - run: apk add -U git
      - checkout
      - run: pip install pre-commit
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit install-hooks
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: pre-commit run --all-files

workflows:
  version: 2
  run-jobs:
    jobs:
      - lint

      # - orb-tools/lint:
      #     lint-dir: circleci-orbs/circleci-deployment-notifier
      # - orb-tools/pack:
      #     source-dir: circleci-orbs/circleci-deployment-notifier
      #     requires:
      #       - orb-tools/lint
      # - orb-tools/publish-dev:
      #     context: org-global
      #     orb-name: thekevjames/deployment-notifier
      #     requires:
      #       - lint
      #       - orb-tools/pack
      # - orb-tools/dev-promote-prod:
      #     context: org-global
      #     orb-name: thekevjames/deployment-notifier
      #     # TODO: allow major and minor semver updates
      #     release: patch
