version: 2.1
description: "Tools for running lint commands"

commands:
  pre-commit:
    description: |
      Runs pre-commit hooks against the current repo. Must be run in an executor with git, python, pip.
    steps:
      - run: python -m pip install pre-commit
      - checkout
      - restore_cache:
          keys:
            - cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit install-hooks
      - save_cache:
          key: cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run: pre-commit run --all-files

jobs:
  pre-commit:
    description: |
      Runs pre-commit hooks against the current repo.
    docker:
      - image: python:<<parameters.python_version>>
    parameters:
      python_version:
        default: 3.7.2
        description: |
          The python version used to run pre-commit.
        type: string
    steps:
      - pre-commit
