# TODO: populate, then publish on crates
[package]
name = "cctui"
version = "0.1.0"
authors = ["Kevin James <KevinJames@thekev.in>"]
edition = "2018"

# description = ""
# readme = ""
# repository = ""
license = "MIT"
# keywords = []  # <=5

[badges]
# circle-ci = { repository = "...", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
chrono = "0.4"
config = { version = "0.10", features = ["yaml"] }
fern = "0.5"
log = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termion = "1.5"
tui = "0.9"
xdg = "2.2"
