version: 2.1
description: "Tools for notifying external services about new deployments"

executors:
  alpine-stable:
    docker:
    - image: alpine:3.9
    resource_class: small

# TODO: document pre-steps and post-steps
jobs:
  slack:
    description: |
      Uses thekevjames/slack-notifier to send a deployment notification to your workspace.
    # TODO: create send-deploy-notif executor
    executor: alpine-stable
    parameters:
      changes:
        default: ''
        description: |
          The (optional) changelog for this release.
        type: string
      diff_url:
        default: ${CIRCLE_COMPARE_URL}
        description: |
          A link to the changeset for this release.
        type: string
      environment:
        default: ${CIRCLE_TAG}
        description: |
          The environment being deployed.
        type: string
      prev_version:
        default: unknown
        description: |
          Previously-released version.
        type: string
      project:
        default: ${CIRCLE_PROJECT_REPONAME}
        description: |
          The name of the project.
        type: string
      user:
        default: ${CIRCLE_USERNAME}
        description: |
          User responsible for this release.
        type: string
      version:
        default: ${CIRCLE_SHA1:0:10}
        description: |
          Newly-released version.
        type: string
    steps:
      - run: apk add -U curl
      - run: curl https://raw.githubusercontent.com/TheKevJames/tools/master/slack-notifier/send-deploy-notif.sh > /send-deploy-notif.sh
      - run: |
          sh /send-deploy-notif.sh \
            -c <<parameters.changes>> \
            -d <<parameters.diff_url>> \
            -e <<parameters.environment>> \
            -n <<parameters.project>> \
            -p <<parameters.prev_version>> \
            -u <<parameters.user>> \
            -v <<parameters.version>>
